services:
  frontend:
    container_name: frontend
    image: rotoyapp.azurecr.io/frontend:latest
    build:
      context: ./platform-frontend
      ssh: 
        ["true"]
    env_file:
      - ./platform-frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - PORT=3000
      - WEBSITES_PORT=3000

    networks:
      - app-network

  backend:
    container_name: backend
    image: rotoyapp.azurecr.io/backend:latest
    build:
      context: ./platform-backend
      ssh:
        ["true"]
      dockerfile: Dockerfile
    env_file:
      - ./platform-backend/.env
    ports:
      - "8181:8181"
    depends_on:
      - db
    environment:
      - PORT=8181
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: rotoy_parent_child_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
